import type { IconName } from "@/types/icon-name";

export const iconMap: Record<IconName, string> = {
  // Social media icons
  'facebook': 'simple-icons:facebook',
  'instagram': 'simple-icons:instagram',
  'paypal': 'simple-icons:paypal',
  'twitter': 'simple-icons:x',
  'github': 'simple-icons:github',
  'dribbble': 'simple-icons:dribbble',
  'linkedin': 'simple-icons:linkedin',
  'youtube': 'simple-icons:youtube',
  'twitch': 'simple-icons:twitch',
  'discord': 'simple-icons:discord',
  'slack': 'simple-icons:slack',
  'reddit': 'simple-icons:reddit',
  'pinterest': 'simple-icons:pinterest',
  'producthunt': 'simple-icons:producthunt',
  'opencollective': 'simple-icons:opencollective',
  
  // Company logos
  'stripe': 'simple-icons:stripe',
  'shopify': 'simple-icons:shopify',
  'notion': 'simple-icons:notion',
  'hubspot': 'simple-icons:hubspot',
  'intercom': 'simple-icons:intercom',
  'linear': 'simple-icons:linear',

    // General icons
  'lightning': 'heroicons:bolt',
  'code': 'heroicons:code-bracket',
  'chart': 'heroicons:chart-bar',
  'chat': 'heroicons:chat-bubble-left-right',
  'shield': 'heroicons:lock-closed',
  'clock': 'heroicons:clock',
  'brush': 'heroicons:paint-brush',
  'layers': 'heroicons:user-group',
  'zap': 'heroicons:arrow-trending-up',
  'star': 'heroicons:star',
  'heart': 'heroicons:heart',
  'bolt': 'heroicons:bolt',
  'users': 'heroicons:user-group',
  'cloud': 'heroicons:cloud',
  'globe': 'heroicons:globe-alt',
  'lock': 'heroicons:lock-closed',
  'shield-x': 'heroicons:shield-exclamation',
  'shield-check': 'heroicons:shield-check',
  'paperplane': 'heroicons:paper-airplane',
  'chevron-right': 'heroicons:chevron-right',
  'chevron-left': 'heroicons:chevron-left',
  'chevron-up': 'heroicons:chevron-up',
  'chevron-down': 'heroicons:chevron-down',
  'cpu-chip': 'heroicons:cpu-chip',
  'wrench': 'heroicons:wrench-screwdriver',
  'question-mark': 'heroicons:question-mark-circle',
};